version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: django
    versions:
    - 2.2.13
  - dependency-name: django-taggit
    versions:
    - 1.3.0
