# Generated by Django 5.1 on 2024-08-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diary_content_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='diary.tag'),
        ),
    ]
