# Generated by Django 6.0.4 on 2026-04-29 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_sharelink"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaryAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("DONE", "Done"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("bangla_content", models.JSONField(blank=True, null=True)),
                (
                    "mood",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("happy", "Happy"),
                            ("sad", "Sad"),
                            ("nostalgic", "Nostalgic"),
                            ("anxious", "Anxious"),
                            ("excited", "Excited"),
                            ("angry", "Angry"),
                            ("calm", "Calm"),
                            ("romantic", "Romantic"),
                            ("reflective", "Reflective"),
                            ("grateful", "Grateful"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("summary", models.TextField(blank=True, default="")),
                (
                    "task_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "diary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="diary.diary",
                    ),
                ),
            ],
        ),
    ]
