# Generated by Django 5.1 on 2024-09-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_diary_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='tags',
            field=models.ManyToManyField(blank=True, to='diary.tag'),
        ),
    ]
