# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20170106_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='iv',
            field=models.CharField(default='.', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='iv',
            field=models.CharField(default='.', max_length=500),
            preserve_default=False,
        ),
    ]
