# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_auto_20170110_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='salt',
            field=models.CharField(default='SSSSS', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='salt',
            field=models.CharField(default='sss', max_length=1000),
            preserve_default=False,
        ),
    ]
