# Generated by Django 6.0.7 on 2026-07-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="web_base_url",
            field=models.URLField(blank=True, default="", max_length=255),
        ),
    ]
