name: Django tests
on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['master']
jobs:
  container-job:
    runs-on: ubuntu-latest
    container: python:3.12-bookworm

    services:
      postgres:
        image: postgres:16.3-alpine3.20
        env:
          POSTGRES_PASSWORD: hiren
          POSTGRES_USER: hiren
          POSTGRES_DB: diary
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test with pytest
        run: pytest -vv
        env:
          SECRET_KEY: xyz1234567890qwerty
          DEBUG: False
          ALLOWED_HOSTS: ['localhost', '127.0.0.1']
          TIMEZONE: Asia/Dhaka
          DB_NAME: diary,
          DB_PASSWORD: hiren,
          DB_USER: hiren,
          DB_HOST: postgres



